version: '3.7'

services:

  nginx:
    build: ./compose/production/nginx
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    ports:
      - 80:80
      - 5555:5555
      - 15672:15672
    depends_on:
      - web
      - flower
      - redis

  web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: web_retailers_scrapper
    restart: on-failure:5 
    command: /start
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - database
      - memcached
      - redis

  database:
    image: postgres:12.0-alpine 
    restart: on-failure:5    
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/      
    environment:
      - POSTGRES_DB=retailer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  memcached:
    image: memcached
    restart: on-failure:5 
    expose:
      - 11211
    entrypoint:
      - memcached
      - -m 64

  redis:
    image: redis:5-alpine
    restart: on-failure:5 
    expose:
      - 6379

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: celery_worker_retailers_scrapper
    restart: on-failure:5 
    command: /start-celeryworker
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - database

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: celery_beat_retailers_scrapper
    restart: on-failure:5 
    command: /start-celerybeat
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - ./.env/.prod-sample
    depends_on:
      - redis
      - database

  flower:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: celey_flower_retailers_scrapper
    restart: on-failure:5 
    command: /start-flower
    volumes:
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - ./.env/.prod-sample
    expose:
      - 5555
    depends_on:
      - redis
      - database    

volumes:
  postgres_data:
  staticfiles:
  mediafiles:   