version: '3.7'

services:

  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: web_retailers_scrapper
    restart: on-failure:5 
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./envs/.dev-sample
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:12.0-alpine 
    restart: on-failure:5    
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/      
    environment:
      - POSTGRES_DB=retailer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:5-alpine
    restart: on-failure:5 

  celeryworker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celery_worker_retailers_scrapper
    restart: on-failure:5 
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./envs/.dev-sample
    depends_on:
      - redis
      - postgres

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celery_beat_retailers_scrapper
    restart: on-failure:5 
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./envs/.dev-sample
    depends_on:
      - redis
      - postgres

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: celey_flower_retailers_scrapper
    restart: on-failure:5 
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./envs/.dev-sample
    ports:
      - 5555:5555
    depends_on:
      - redis
      - postgres    

volumes:
  postgres_data:      