#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A retailers_scrapper inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 60
done
>&2 echo 'Celery workers is available'

celery flower \
    --app=retailers_scrapper \
    --broker="${CELERY_BROKER}"
