# Generated by Django 3.1.5 on 2021-01-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='card_promotion_price',
        ),
        migrations.AddField(
            model_name='product',
            name='card_promotion_price',
            field=models.ManyToManyField(blank=True, null=True, related_name='card_promotion_prices', related_query_name='card_promotion_price', to='products.Price'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotion_price',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_price',
            field=models.ManyToManyField(blank=True, null=True, related_name='promotion_prices', related_query_name='promotion_price', to='products.Price'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='regular_price',
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.ManyToManyField(blank=True, null=True, related_name='regular_prices', related_query_name='regular_price', to='products.Price'),
        ),
    ]
