# Generated by Django 3.1.5 on 2021-01-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210121_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_weight_unit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
