# Generated by Django 3.1.5 on 2021-02-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210131_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_promotion_price',
            field=models.ManyToManyField(blank=True, related_name='card_promotion_prices', related_query_name='card_promotion_price', to='products.Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion_price',
            field=models.ManyToManyField(blank=True, related_name='promotion_prices', related_query_name='promotion_price', to='products.Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.ManyToManyField(blank=True, related_name='regular_prices', related_query_name='regular_price', to='products.Price'),
        ),
    ]
